### ISSUE TITLE
`fontStyle` not working.

### ISSUE THREAD

**Issue by Ayfri** [Vap0r1ze/vpc-shiki#4]
Hi, I'm making my own theme and I found that putting this:
```json
"settings": {
	"fontStyle": "italic"
}
```
Doesn't work, but putting a `foreground` works so it's not the scope that fails.

**Comment by Vap0r1ze** [comment]
This isn't possible to do with shiki as is, I plan on making this possible on [Vap0r1ze/shiki](https://github.com/Vap0r1ze/shiki) soon. When I do I'll add support for font styles and weights to this plugin.

**Comment by Vap0r1ze** [comment]
Just pushed an update that should add bold and italic support
![image](https://user-images.githubusercontent.com/20448879/111595769-d7ce3800-87a2-11eb-8465-947d975e4c7f.png)

**Comment by Vap0r1ze** [comment]
Now that I've pushed fe16e2e, underline should be supported, as well as combinations of the 3.
