### ISSUE TITLE
How can I put multiple fontStyle ?

### ISSUE THREAD

**Issue by Ayfri** [Vap0r1ze/vpc-shiki#5]
Hi, if I want something bold & italic, how can I do it?
I tried this but it doesn't work:
```json
 "fontStyle": ["bold", "italic"]
```
Neither bold nor italic are applied.

**Comment by Vap0r1ze** [comment]
[After reading this](https://github.com/microsoft/vscode-textmate/blob/6e5409de4591f1cf52f1862f7b1d1399e1feebb9/src/theme.ts#L106-L125) It looks like you should try `"fontStyle": "bold italic"`, let me know if that works

**Comment by Ayfri** [comment]
Nice, it works, thanks!
