### ISSUE TITLE
Python syntax highlight uses python2 syntax

### ISSUE THREAD

**Issue by Lunarequest** [Vap0r1ze/vpc-shiki#8]
python 2 has been depreciated since jan 1st 2020 and uses a different incompatible syntax to python 3. this plugin currently highlights the older deprecated syntax but not the newer python 3 syntax. a example of where this is visible is with the print statement. 
This is acceptable in python 2 but not 3
```python
print "hello world"
```
this is acceptable in python 3 but not 2
```python
print("Hello World")
```
I was wondering how can I help contribute by updating the syntax to modern versions of python

**Comment by Vap0r1ze** [comment]
it seems to highlight both for me

![image](https://user-images.githubusercontent.com/20448879/112325886-6f8fc280-8c8a-11eb-9953-aeb9d7345959.png)

can you show an example of it not highlighting correctly with python 3 syntax

**Comment by Lunarequest** [comment]
![Screenshot_20210324_195937](https://user-images.githubusercontent.com/30698906/112327719-b063f780-8cdb-11eb-9674-cc4b501a9c10.png)
![Screenshot_20210324_195548](https://user-images.githubusercontent.com/30698906/112327728-b22dbb00-8cdb-11eb-87be-89afbe30c267.png)
as you can see it doesn't highlight the python 3 print statement properly

**Comment by Vap0r1ze** [comment]
it looks like you're using the default discord highlighter, not the plugin's highlighter. check your settings

**Comment by Lunarequest** [comment]
yeah I'm sorry I had the discord highlighter set, however the python syntax highlighting doesn't support features introduced in newer versions of python such as `case` and the alternative union methods

**Comment by Vap0r1ze** [comment]
those features are [only drafts](https://docs.python.org/3.10/whatsnew/3.10.html), they aren't supported in much yet. when they land support in vscode, I will probably import the textmate grammar files.

**Comment by Vap0r1ze** [comment]
thanks for taking the time to report a potential bug though, I appreciate the effort
